name: media_kit_test
description: A minimal application for demonstrating & testing package:media_kit
homepage: https://github.com/alexmercerind/media_kit
repository: https://github.com/alexmercerind/media_kit
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  media_kit:
    path: ../media_kit
  media_kit_video:
    path: ../media_kit_video
  media_kit_native_event_loop:
    path: ../media_kit_native_event_loop
  media_kit_libs_windows_video:
    path: ../media_kit_libs_windows_video
  media_kit_libs_linux:
    path: ../media_kit_libs_linux
  media_kit_libs_macos_video:
    path: ../media_kit_libs_macos_video
  media_kit_libs_ios_video:
    path: ../media_kit_libs_ios_video

  file_picker: ^5.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Assets for testing video playback.
  assets:
    - assets/video_0.mp4
    - assets/video_1.mp4
    - assets/video_2.mp4
    - assets/video_3.mp4
    - assets/video_4.mp4
